version: '3.8'

services:
  # Development service - use this on your work computer
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot-reload
      - .:/app
      # Use anonymous volume for node_modules to prevent conflicts
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

  # Production-like service (optional - for testing production builds)
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    profiles:
      - production
