import { PlanningApplication } from './schemas';

export const mockApplications: PlanningApplication[] = [
  {
    id: '1',
    reference: 'PA-2025-001',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Green Development Ltd',
    address: '11 Abbey Gardens, London, SE16 3RQ',
    description: 'Pre-application advice for the proposed construction of a rear extension to the existing residential property. The extension will add approximately 25 square metres of additional living space, including a kitchen extension and garden room with bi-fold doors opening onto the rear garden.',
    status: 'under-review',
    submittedDate: '2025-10-06',
    validFrom: '2025-10-06',
    consultationEnd: '2025-10-27',
    expiryDate: '2025-10-30',
    isPublic: false,
    assignedTo: 'Federico Carbo',
    assignedOfficer: {
      id: 'officer-fc',
      name: 'Federico Carbo',
    },
    requestedServices: ['written-advice', 'site-visit', 'meeting'],
    constraints: [
      {
        id: 'c1',
        type: 'conservation-area',
        label: 'Conservation Area',
        status: 'applies',
        details: 'Bermondsey Street Conservation Area',
      },
      {
        id: 'c2',
        type: 'listed-building',
        label: 'Listed Building',
        status: 'nearby',
        details: 'Grade II listed building within 50m',
      },
      {
        id: 'c3',
        type: 'tpo',
        label: 'Tree Preservation Orders',
        status: 'does-not-apply',
      },
      {
        id: 'c4',
        type: 'flood-risk',
        label: 'Flood Risk',
        status: 'does-not-apply',
        value: 'Zone 1',
      },
      {
        id: 'c5',
        type: 'green-belt',
        label: 'Green Belt / MOL',
        status: 'does-not-apply',
      },
      {
        id: 'c6',
        type: 'article-4',
        label: 'Article 4 Direction',
        status: 'applies',
        details: 'Modified Direction 1 - CAZ',
      },
      {
        id: 'c7',
        type: 'article-4',
        label: 'Article 4 Direction',
        status: 'applies',
        details: 'Modified Direction 2 - KIBAs and WNCBC',
      },
      {
        id: 'c8',
        type: 'archaeology',
        label: 'Archaeological Priority Area',
        status: 'applies',
        details: 'Tier 2 - Bermondsey Abbey',
      },
    ],
    documents: [
      // Drawings
      { id: 'd1', name: 'Proposed Site Plan', category: 'drawings' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '2.4 MB', fileType: 'pdf' as const },
      { id: 'd2', name: 'Existing Floor Plans', category: 'drawings' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '1.8 MB', fileType: 'pdf' as const },
      { id: 'd3', name: 'Proposed Floor Plans', category: 'drawings' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '2.1 MB', fileType: 'pdf' as const },
      { id: 'd4', name: 'Elevation Drawings - South & West', category: 'drawings' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '1.5 MB', fileType: 'pdf' as const },
      // Supporting documents
      { id: 's1', name: 'Pre-Application Form', category: 'supporting' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '456 KB', fileType: 'pdf' as const },
      { id: 's2', name: 'Design & Access Statement', category: 'supporting' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '3.2 MB', fileType: 'pdf' as const },
      { id: 's3', name: 'Planning Statement', category: 'supporting' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '1.1 MB', fileType: 'pdf' as const },
      { id: 's4', name: 'Heritage Impact Assessment', category: 'supporting' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-07', fileSize: '2.8 MB', fileType: 'pdf' as const },
      // Evidence
      { id: 'e1', name: 'Existing Rear Elevation Photo', category: 'evidence' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '3.5 MB', fileType: 'jpg' as const },
      { id: 'e2', name: 'Garden Context Photo', category: 'evidence' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '4.1 MB', fileType: 'jpg' as const },
      { id: 'e3', name: 'Street View Photo', category: 'evidence' as const, uploadedBy: 'Green Development Ltd', uploadedDate: '2025-10-06', fileSize: '3.8 MB', fileType: 'jpg' as const },
      { id: 'e4', name: 'Neighbor Context Photos', category: 'evidence' as const, uploadedBy: 'Federico Carbo', uploadedDate: '2025-10-08', fileSize: '5.2 MB', fileType: 'jpg' as const },
    ],
    // Stage workflow - validated, both consultation and assessment active
    validationStatus: 'validated',
    validationDate: '2025-10-06',
    consultationStatus: 'in-progress',
    consultationStartDate: '2025-10-06',
    assessmentStatus: 'in-progress',
    assessmentStartDate: '2025-10-08',
    reviewStatus: 'not-started',
    // Enhanced stage workflow with tasks
    validation: {
      status: 'validated',
      validatedDate: '2025-10-06',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2025-10-06' },
        { id: 'v2', title: 'Verify fee payment', completed: true, completedDate: '2025-10-06' },
        { id: 'v3', title: 'Confirm site ownership', completed: true, completedDate: '2025-10-06' },
        { id: 'v4', title: 'Review supporting documents', completed: true, completedDate: '2025-10-06' },
      ],
    },
    consultation: {
      status: 'in-progress',
      startDate: '2025-10-06',
      endDate: '2025-10-27',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: true, completedDate: '2025-10-06' },
        { id: 'c2', title: 'Post site notice', completed: true, completedDate: '2025-10-07' },
        { id: 'c3', title: 'Notify neighbours', completed: true, completedDate: '2025-10-07' },
        { id: 'c4', title: 'Review consultation responses', completed: false },
        { id: 'c5', title: 'Prepare consultation summary', completed: false },
      ],
    },
    assessment: {
      status: 'in-progress',
      startDate: '2025-10-08',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: true, completedDate: '2025-10-08' },
        { id: 'a2', title: 'Assess design and appearance', completed: true, completedDate: '2025-10-09' },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: false },
        { id: 'a4', title: 'Check conservation considerations', completed: false },
        { id: 'a5', title: 'Prepare recommendation report', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Legal check', completed: false },
        { id: 'r3', title: 'Final decision', completed: false },
      ],
    },
  },
  {
    id: '2',
    reference: 'PA-2025-002',
    type: 'full-application',
    applicationType: 'Full Planning Permission',
    applicantName: 'Citywide Construction',
    address: '456 High Road, Manchester, M1 1AB',
    description: 'Commercial building renovation and expansion',
    status: 'pending',
    submittedDate: '2025-02-01',
    validFrom: '2025-02-01',
    consultationEnd: '2025-02-22',
    expiryDate: '2025-05-01',
    isPublic: true,
    // Stage workflow - still pending validation
    validationStatus: 'pending',
    consultationStatus: 'not-started',
    assessmentStatus: 'not-started',
    reviewStatus: 'not-started',
    // Enhanced stage workflow with tasks
    validation: {
      status: 'pending',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2025-02-01' },
        { id: 'v2', title: 'Verify fee payment', completed: false },
        { id: 'v3', title: 'Confirm site ownership', completed: false },
        { id: 'v4', title: 'Review supporting documents', completed: false },
      ],
    },
    consultation: {
      status: 'not-started',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: false },
        { id: 'c2', title: 'Post site notice', completed: false },
        { id: 'c3', title: 'Notify neighbours', completed: false },
        { id: 'c4', title: 'Review consultation responses', completed: false },
        { id: 'c5', title: 'Prepare consultation summary', completed: false },
      ],
    },
    assessment: {
      status: 'not-started',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: false },
        { id: 'a2', title: 'Assess design and appearance', completed: false },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: false },
        { id: 'a4', title: 'Check conservation considerations', completed: false },
        { id: 'a5', title: 'Prepare recommendation report', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Legal check', completed: false },
        { id: 'r3', title: 'Final decision', completed: false },
      ],
    },
  },
  {
    id: '3',
    reference: 'PA-2025-003',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Heritage Homes',
    address: '789 Park Lane, Birmingham, B1 1BB',
    description: 'Conservation area development consultation',
    status: 'approved',
    submittedDate: '2024-12-10',
    validFrom: '2024-12-10',
    consultationEnd: '2024-12-31',
    expiryDate: '2025-01-10',
    isPublic: true,
    assignedTo: 'Bob Smith',
    assignedOfficer: {
      id: 'officer-bs',
      name: 'Bob Smith',
    },
    // Stage workflow - completed all stages
    validationStatus: 'validated',
    validationDate: '2024-12-10',
    consultationStatus: 'completed',
    consultationStartDate: '2024-12-10',
    assessmentStatus: 'completed',
    assessmentStartDate: '2024-12-12',
    reviewStatus: 'completed',
    reviewStartDate: '2025-01-05',
    // Enhanced stage workflow with tasks
    validation: {
      status: 'validated',
      validatedDate: '2024-12-10',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2024-12-10' },
        { id: 'v2', title: 'Verify fee payment', completed: true, completedDate: '2024-12-10' },
        { id: 'v3', title: 'Confirm site ownership', completed: true, completedDate: '2024-12-10' },
        { id: 'v4', title: 'Review supporting documents', completed: true, completedDate: '2024-12-10' },
      ],
    },
    consultation: {
      status: 'completed',
      startDate: '2024-12-10',
      endDate: '2024-12-31',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: true, completedDate: '2024-12-10' },
        { id: 'c2', title: 'Post site notice', completed: true, completedDate: '2024-12-11' },
        { id: 'c3', title: 'Notify neighbours', completed: true, completedDate: '2024-12-11' },
        { id: 'c4', title: 'Review consultation responses', completed: true, completedDate: '2024-12-30' },
        { id: 'c5', title: 'Prepare consultation summary', completed: true, completedDate: '2024-12-31' },
      ],
    },
    assessment: {
      status: 'completed',
      startDate: '2024-12-12',
      completedDate: '2025-01-04',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: true, completedDate: '2024-12-12' },
        { id: 'a2', title: 'Assess design and appearance', completed: true, completedDate: '2024-12-15' },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: true, completedDate: '2024-12-20' },
        { id: 'a4', title: 'Check conservation considerations', completed: true, completedDate: '2024-12-28' },
        { id: 'a5', title: 'Prepare recommendation report', completed: true, completedDate: '2025-01-04' },
      ],
    },
    review: {
      status: 'completed',
      startDate: '2025-01-05',
      completedDate: '2025-01-10',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: true, completedDate: '2025-01-05' },
        { id: 'r2', title: 'Legal check', completed: true, completedDate: '2025-01-08' },
        { id: 'r3', title: 'Final decision', completed: true, completedDate: '2025-01-10' },
      ],
    },
  },
];
