import { PlanningApplication } from './schemas';

export const mockApplications: PlanningApplication[] = [
  {
    id: '1',
    reference: 'PA-2025-001',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Green Development Ltd',
    address: '11 Abbey Gardens, London, SE16 3RQ',
    description: 'Pre-application advice for the proposed construction of a rear extension to the existing residential property. The extension will add approximately 25 square metres of additional living space, including a kitchen extension and garden room with bi-fold doors opening onto the rear garden.',
    status: 'under-review',
    submittedDate: '2025-10-06',
    validFrom: '2025-10-06',
    consultationEnd: '2025-10-27',
    expiryDate: '2025-10-30',
    isPublic: false,
    assignedTo: 'Federico Carbo',
    assignedOfficer: {
      id: 'officer-fc',
      name: 'Federico Carbo',
    },
  },
  {
    id: '2',
    reference: 'PA-2025-002',
    type: 'full-application',
    applicationType: 'Full Planning Permission',
    applicantName: 'Citywide Construction',
    address: '456 High Road, Manchester, M1 1AB',
    description: 'Commercial building renovation and expansion',
    status: 'pending',
    submittedDate: '2025-02-01',
    validFrom: '2025-02-01',
    consultationEnd: '2025-02-22',
    expiryDate: '2025-05-01',
    isPublic: true,
  },
  {
    id: '3',
    reference: 'PA-2025-003',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Heritage Homes',
    address: '789 Park Lane, Birmingham, B1 1BB',
    description: 'Conservation area development consultation',
    status: 'approved',
    submittedDate: '2024-12-10',
    validFrom: '2024-12-10',
    consultationEnd: '2024-12-31',
    expiryDate: '2025-01-10',
    isPublic: true,
    assignedTo: 'Bob Smith',
    assignedOfficer: {
      id: 'officer-bs',
      name: 'Bob Smith',
    },
  },
];
