import { PlanningApplication } from './schemas';
import {
  bermondseyStreetConservationArea,
  stMaryMagdalenChurch,
  bermondseyArticle4Direction,
} from './constraint-geometries';

export const mockApplications: PlanningApplication[] = [
  {
    id: '1',
    reference: 'PA-2025-001',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'John Smith',
    address: '75, MAIN STREET, DONCASTER, DN9 3HW',
    description: 'Add a conservatory onto the rear of my first storey to use as a reading room and library.',
    status: 'in-assessment',
    submittedDate: '2025-10-06',
    validFrom: '2025-10-06',
    consultationEnd: '2025-10-27',
    expiryDate: '2025-10-30',
    isPublic: false,
    assignedTo: 'Federico Carbo',
    assignedOfficer: {
      id: 'officer-fc',
      name: 'Federico Carbo',
    },
    parish: 'Auckley',
    ward: 'Finningley',
    wardType: 'Metropolitan district ward',
    uprn: '100050747612',
    workStarted: false,
    paymentReference: '8tdudifjrg7va2ud2nptc6iedf',
    paymentAmount: 450.00,
    sessionId: '1a768034-c07a-4cd5-92b6-fc4a1fd0abd4',
    locationUrl: 'https://www.google.com/maps/search/?api=1&query=75+MAIN+STREET+DONCASTER+DN9+3HW',
    requestedServices: ['written-advice', 'site-visit', 'meeting'],
    serviceRecords: [
      {
        id: 'sr-1',
        service: 'written-advice',
        status: 'included',
        cost: 500,
      },
      {
        id: 'sr-2',
        service: 'site-visit',
        status: 'included',
        cost: 200,
      },
      {
        id: 'sr-3',
        service: 'meeting',
        status: 'included',
        cost: 300,
      },
    ],
    totalServiceCost: 1000,
    constraints: [
      {
        id: 'c1',
        type: 'conservation-area',
        label: 'Conservation area',
        entity: 'Bermondsey Street',
        status: 'applies',
        category: 'Heritage and conservation',
        source: 'Planning Data',
        color: '#7C2D55',
        geometry: {
          type: 'MultiPolygon',
          coordinates: [bermondseyStreetConservationArea]
        },
        planningDataEntity: 44010255,
        reference: '2',
      },
      {
        id: 'c2',
        type: 'listed-building',
        label: 'Listed building',
        entity: 'Church of St Mary Magdalene',
        status: 'nearby',
        category: 'Heritage and conservation',
        source: 'Historic England',
        color: '#9C4E97',
        value: 'Grade II*',
        geometry: {
          type: 'Point',
          coordinates: stMaryMagdalenChurch
        },
        planningDataEntity: 31814493,
        reference: '1376567',
      },
      {
        id: 'c3',
        type: 'article-4',
        label: 'Article 4 direction',
        entity: 'Galleywall and Bermondsey Trading Estates',
        status: 'applies',
        category: 'General policy',
        source: 'Planning Data',
        color: '#D4A02F',
        details: 'Restricts demolition of commercial buildings',
        geometry: {
          type: 'MultiPolygon',
          coordinates: [bermondseyArticle4Direction]
        },
        planningDataEntity: 7010003619,
        reference: '203',
      },
    ],
    documents: [
      // Drawings
      {
        id: 'd1',
        name: 'DRA-001-Site_Plan.pdf',
        category: 'drawings' as const,
        uploadedDate: '2025-10-06',
        fileSize: '2.4 MB',
        fileType: 'pdf' as const,
        tags: ['Site plan - proposed'],
        version: 'v2',
        visibility: 'public' as const
      },
      {
        id: 'd2',
        name: 'DRA-002-Proposed_Existing_Drawings.pdf',
        category: 'drawings' as const,
        uploadedDate: '2025-10-06',
        fileSize: '3.9 MB',
        fileType: 'pdf' as const,
        tags: ['Elevations - existing', 'Floor plan - existing', 'Elevations - proposed', 'Floor plan - proposed'],
        version: 'v1',
        visibility: 'public' as const
      },
      {
        id: 'd3',
        name: 'DRA-003-Sections.pdf',
        category: 'drawings' as const,
        uploadedDate: '2025-10-06',
        fileSize: '2.1 MB',
        fileType: 'pdf' as const,
        tags: ['Sections - existing', 'Sections - proposed'],
        version: 'v1',
        visibility: 'public' as const
      },
      // Supporting documents
      {
        id: 's1',
        name: 'SUP-001-Pre_Application_Form.pdf',
        category: 'supporting' as const,
        uploadedDate: '2025-10-06',
        fileSize: '456 KB',
        fileType: 'pdf' as const,
        tags: ['Application form'],
        visibility: 'sensitive' as const
      },
      {
        id: 's2',
        name: 'SUP-002-Design_Access_Statement.pdf',
        category: 'supporting' as const,
        uploadedDate: '2025-10-06',
        fileSize: '3.2 MB',
        fileType: 'pdf' as const,
        tags: ['Design statement', 'Access statement'],
        version: 'v3',
        visibility: 'public' as const
      },
      {
        id: 's3',
        name: 'SUP-003-Planning_Statement.pdf',
        category: 'supporting' as const,
        uploadedDate: '2025-10-06',
        fileSize: '1.1 MB',
        fileType: 'pdf' as const,
        tags: ['Planning statement'],
        version: 'v2',
        visibility: 'public' as const
      },
      {
        id: 's4',
        name: 'SUP-004-Heritage_Impact_Assessment.pdf',
        category: 'supporting' as const,
        uploadedDate: '2025-10-07',
        fileSize: '2.8 MB',
        fileType: 'pdf' as const,
        tags: ['Heritage assessment'],
        version: 'v1',
        visibility: 'public' as const
      },
      // Evidence
      {
        id: 'e1',
        name: 'PHO-001-Rear_Elevation.jpg',
        category: 'evidence' as const,
        uploadedDate: '2025-10-06',
        fileSize: '3.5 MB',
        fileType: 'jpg' as const,
        tags: ['Site photos'],
        visibility: 'public' as const
      },
      {
        id: 'e2',
        name: 'PHO-002-Garden_Context.jpg',
        category: 'evidence' as const,
        uploadedDate: '2025-10-06',
        fileSize: '4.1 MB',
        fileType: 'jpg' as const,
        tags: ['Site photos'],
        visibility: 'public' as const
      },
      {
        id: 'e3',
        name: 'PHO-003-Street_View.jpg',
        category: 'evidence' as const,
        uploadedDate: '2025-10-06',
        fileSize: '3.8 MB',
        fileType: 'jpg' as const,
        tags: ['Site photos', 'Street scene'],
        visibility: 'public' as const
      },
      {
        id: 'e4',
        name: 'PHO-004-Neighbor_Context.jpg',
        category: 'evidence' as const,
        uploadedDate: '2025-10-08',
        fileSize: '5.2 MB',
        fileType: 'jpg' as const,
        tags: ['Site photos', 'Neighbor context'],
        visibility: 'sensitive' as const
      },
    ],
    consulteeConsultation: {
      totalConsultees: 5,
      totalResponses: 4,
      noObjectionCount: 3,
      objectionCount: 0,
      amendmentsNeededCount: 1,
      notContactedCount: 1,
      awaitingResponseCount: 0,
      briefSummary: 'Most statutory consultees have no objections to the proposal. Historic England has no objection, noting the design respects the conservation area character. The Conservation Officer has no objection subject to materials being approved, and the Tree Officer recommends a condition for tree protection during construction. The Design Review Panel suggests amendments to improve the interface with the neighboring listed building. Thames Water has not been contacted as the proposal does not impact water infrastructure.',
      responses: [
        {
          id: 'cr1',
          consulteeOrg: 'Historic England',
          type: 'external',
          responseDate: '2025-10-15',
          position: 'no-objection',
          summary: 'No objection. Design is sympathetic to conservation area character with appropriate materials and scale that respects the surrounding historic context.',
          commentCount: 2,
        },
        {
          id: 'cr2',
          consulteeOrg: 'Conservation Officer',
          type: 'internal',
          responseDate: '2025-10-14',
          position: 'no-objection',
          summary: 'Supports application with condition requiring prior approval of external material samples including brickwork, roofing tiles, and window frames.',
          commentCount: 3,
        },
        {
          id: 'cr3',
          consulteeOrg: 'Tree Officer',
          type: 'internal',
          responseDate: '2025-10-16',
          position: 'no-objection',
          summary: 'No objection. Recommends condition for tree protection fencing in accordance with BS5837 to safeguard protected oak during construction.',
          commentCount: 1,
        },
        {
          id: 'cr4',
          consulteeOrg: 'Design Review Panel',
          type: 'external',
          responseDate: '2025-10-17',
          position: 'amendments-needed',
          summary: 'Concerns about fenestration on east elevation not responding to adjacent listed building. Recommends revising window arrangement to reflect traditional Victorian proportions.',
          commentCount: 5,
        },
        {
          id: 'cr5',
          consulteeOrg: 'Thames Water',
          type: 'external',
          position: 'not-contacted',
          commentCount: 0,
        },
      ],
    },
    neighbourConsultation: {
      totalNotified: 34,
      totalResponses: 8,
      supportCount: 2,
      objectCount: 5,
      neutralCount: 1,
      briefSummary: 'Most neighbours are against this proposal, with five objections, two in support, and one neutral comment. The main worry is about losing natural light - four people who live nearby say their kitchens and gardens will be darker, especially those at numbers 9 and 13 who share a boundary with the property. People also raised concerns about privacy from the new windows overlooking their gardens, the appearance of the modern materials like bi-fold doors in this Victorian street, construction noise and traffic, and potential damage to the shared access road. The two neighbours who support the application think the design is well thought out and won\'t negatively affect surrounding properties.',
      topicSummaries: [
        {
          topic: 'design',
          label: 'Design',
          count: 3,
          aiSummary: 'Three neighbours commented on the design of the proposed extension. Concerns were raised about the modern materials, particularly the bi-fold doors, which some feel are not in keeping with the Victorian character of the surrounding properties. However, other respondents found the design to be well-considered and appropriate for the context.'
        },
        {
          topic: 'privacy',
          label: 'Privacy',
          count: 2,
          aiSummary: 'Two neighbours raised concerns about privacy impacts from the proposed extension. The main issue is the new windows that will overlook adjacent gardens, particularly affecting properties at numbers 9 and 11. Residents worry about the loss of privacy in their outdoor spaces.'
        },
        {
          topic: 'loss-of-light',
          label: 'Loss of light',
          count: 4,
          aiSummary: 'Loss of light is the most frequently raised concern, with four neighbours commenting on this issue. Residents at numbers 9 and 13, who share boundaries with the property, are particularly worried about reduced natural light to their kitchens and gardens. The proposed rear extension is seen as likely to cause significant overshadowing during key times of the day.'
        },
        {
          topic: 'traffic',
          label: 'Traffic',
          count: 1,
          aiSummary: 'One neighbour raised concerns about construction traffic and potential damage to the shared access road during the building works. There are also worries about parking impacts during the construction period.'
        },
        {
          topic: 'accessibility',
          label: 'Accessibility',
          count: 0,
          aiSummary: ''
        },
        {
          topic: 'noise',
          label: 'Noise',
          count: 2,
          aiSummary: 'Two neighbours commented on noise concerns, primarily focused on construction noise during the building works. There are worries about the duration of the works and the impact on working from home arrangements and young children in adjacent properties.'
        },
      ],
      responses: [
        {
          id: 'nr1',
          respondentName: 'Sarah Mitchell',
          address: '9 Abbey Gardens',
          responseDate: '2025-10-12',
          position: 'object',
          topics: ['loss-of-light', 'privacy'],
          summary: 'Concerned about loss of light to kitchen and dining room. Property shares boundary with proposed extension.',
        },
        {
          id: 'nr2',
          respondentName: 'David Chen',
          address: '13 Abbey Gardens',
          responseDate: '2025-10-13',
          position: 'object',
          topics: ['loss-of-light', 'privacy', 'noise'],
          summary: 'Objects due to overlooking from proposed first-floor windows and potential noise during construction.',
        },
        {
          id: 'nr3',
          respondentName: 'Margaret Thompson',
          address: '15 Abbey Gardens',
          responseDate: '2025-10-14',
          position: 'support',
          topics: ['design'],
          summary: 'Supports the application. Notes the design is sympathetic and will improve the streetscape.',
        },
        {
          id: 'nr4',
          respondentName: 'James Wilson',
          address: '7 Abbey Gardens',
          responseDate: '2025-10-14',
          position: 'object',
          topics: ['design'],
          summary: 'Concerned about impact on conservation area character. Modern materials not appropriate for Victorian terrace.',
        },
        {
          id: 'nr5',
          respondentName: 'Emma Roberts',
          address: '17 Abbey Gardens',
          responseDate: '2025-10-15',
          position: 'neutral',
          topics: ['noise'],
          summary: 'No objection but requests construction hours be limited to 8am-6pm Monday to Friday.',
        },
        {
          id: 'nr6',
          respondentName: 'Peter Johnson',
          address: '5 Abbey Gardens',
          responseDate: '2025-10-16',
          position: 'object',
          topics: ['loss-of-light', 'design'],
          summary: 'Extension is too large and will dominate neighbouring gardens. Concerns about precedent for similar developments.',
        },
        {
          id: 'nr7',
          respondentName: 'Lisa Anderson',
          address: '19 Abbey Gardens',
          responseDate: '2025-10-17',
          position: 'support',
          topics: ['design'],
          summary: 'Well-designed extension that respects the character of the area. No impact on our property.',
        },
        {
          id: 'nr8',
          respondentName: 'Robert Davies',
          address: '3 Abbey Gardens',
          responseDate: '2025-10-18',
          position: 'object',
          topics: ['traffic', 'loss-of-light'],
          summary: 'Concerned about increased traffic during construction and potential damage to shared access road.',
        },
      ],
    },
    // Stage workflow with tasks - validated, both consultation and assessment active
    validation: {
      status: 'validated',
      validatedDate: '2025-10-06',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2025-10-06' },
        { id: 'v2', title: 'Verify fee payment', completed: true, completedDate: '2025-10-06' },
        { id: 'v3', title: 'Confirm site ownership', completed: true, completedDate: '2025-10-06' },
        { id: 'v4', title: 'Review supporting documents', completed: true, completedDate: '2025-10-06' },
      ],
    },
    consultation: {
      status: 'in-progress',
      startDate: '2025-10-06',
      endDate: '2025-10-27',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: true, completedDate: '2025-10-06' },
        { id: 'c2', title: 'Post site notice', completed: true, completedDate: '2025-10-07' },
        { id: 'c3', title: 'Notify neighbours', completed: true, completedDate: '2025-10-07' },
        { id: 'c4', title: 'Review consultation responses', completed: false },
        { id: 'c5', title: 'Prepare consultation summary', completed: false },
      ],
    },
    assessment: {
      status: 'in-progress',
      startDate: '2025-10-08',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: true, completedDate: '2025-10-08' },
        { id: 'a2', title: 'Assess design and appearance', completed: true, completedDate: '2025-10-09' },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: false },
        { id: 'a4', title: 'Check conservation considerations', completed: false },
        { id: 'a5', title: 'Prepare recommendation report', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Legal check', completed: false },
        { id: 'r3', title: 'Final decision', completed: false },
      ],
    },
  },
  {
    id: '2',
    reference: 'PA-2025-002',
    type: 'full-application',
    applicationType: 'Full Planning Permission',
    applicantName: 'Citywide Construction',
    address: '456 High Road, Manchester, M1 1AB',
    description: 'Commercial building renovation and expansion',
    status: 'pending',
    submittedDate: '2025-02-01',
    validFrom: '2025-02-01',
    consultationEnd: '2025-02-22',
    expiryDate: '2025-05-01',
    isPublic: true,
    // Stage workflow with tasks - still pending validation
    validation: {
      status: 'pending',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2025-02-01' },
        { id: 'v2', title: 'Verify fee payment', completed: false },
        { id: 'v3', title: 'Confirm site ownership', completed: false },
        { id: 'v4', title: 'Review supporting documents', completed: false },
      ],
    },
    consultation: {
      status: 'not-started',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: false },
        { id: 'c2', title: 'Post site notice', completed: false },
        { id: 'c3', title: 'Notify neighbours', completed: false },
        { id: 'c4', title: 'Review consultation responses', completed: false },
        { id: 'c5', title: 'Prepare consultation summary', completed: false },
      ],
    },
    assessment: {
      status: 'not-started',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: false },
        { id: 'a2', title: 'Assess design and appearance', completed: false },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: false },
        { id: 'a4', title: 'Check conservation considerations', completed: false },
        { id: 'a5', title: 'Prepare recommendation report', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Legal check', completed: false },
        { id: 'r3', title: 'Final decision', completed: false },
      ],
    },
  },
  {
    id: '3',
    reference: 'PA-2025-003',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Heritage Homes',
    address: '789 Park Lane, Birmingham, B1 1BB',
    description: 'Conservation area development consultation',
    status: 'closed',
    outcome: 'likely-supported',
    outcomeDate: '2025-04-15',
    submittedDate: '2024-12-10',
    validFrom: '2024-12-10',
    consultationEnd: '2024-12-31',
    expiryDate: '2025-01-10',
    isPublic: true,
    assignedTo: 'Bob Smith',
    assignedOfficer: {
      id: 'officer-bs',
      name: 'Bob Smith',
    },
    // Stage workflow with tasks - completed all stages
    validation: {
      status: 'validated',
      validatedDate: '2024-12-10',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2024-12-10' },
        { id: 'v2', title: 'Verify fee payment', completed: true, completedDate: '2024-12-10' },
        { id: 'v3', title: 'Confirm site ownership', completed: true, completedDate: '2024-12-10' },
        { id: 'v4', title: 'Review supporting documents', completed: true, completedDate: '2024-12-10' },
      ],
    },
    consultation: {
      status: 'completed',
      startDate: '2024-12-10',
      endDate: '2024-12-31',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: true, completedDate: '2024-12-10' },
        { id: 'c2', title: 'Post site notice', completed: true, completedDate: '2024-12-11' },
        { id: 'c3', title: 'Notify neighbours', completed: true, completedDate: '2024-12-11' },
        { id: 'c4', title: 'Review consultation responses', completed: true, completedDate: '2024-12-30' },
        { id: 'c5', title: 'Prepare consultation summary', completed: true, completedDate: '2024-12-31' },
      ],
    },
    assessment: {
      status: 'completed',
      startDate: '2024-12-12',
      completedDate: '2025-01-04',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: true, completedDate: '2024-12-12' },
        { id: 'a2', title: 'Assess design and appearance', completed: true, completedDate: '2024-12-15' },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: true, completedDate: '2024-12-20' },
        { id: 'a4', title: 'Check conservation considerations', completed: true, completedDate: '2024-12-28' },
        { id: 'a5', title: 'Prepare recommendation report', completed: true, completedDate: '2025-01-04' },
      ],
    },
    review: {
      status: 'completed',
      startDate: '2025-01-05',
      completedDate: '2025-01-10',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: true, completedDate: '2025-01-05' },
        { id: 'r2', title: 'Legal check', completed: true, completedDate: '2025-01-08' },
        { id: 'r3', title: 'Final decision', completed: true, completedDate: '2025-01-10' },
      ],
    },
  },
  {
    id: '4',
    reference: 'PA-2025-004',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Sarah Johnson',
    address: '23 Oak Street, Leeds, LS2 8BB',
    description: 'Loft conversion with dormer windows',
    status: 'not-started',
    submittedDate: '2025-10-28',
    validFrom: '2025-10-28',
    consultationEnd: '2025-11-18',
    expiryDate: '2025-11-30',
    isPublic: false,
    requestedServices: ['written-advice'],
    serviceRecords: [
      {
        id: 'sr-4-1',
        service: 'written-advice',
        status: 'included',
        cost: 500,
      },
    ],
    totalServiceCost: 500,
    constraints: [],
    documents: [],
    validation: {
      status: 'pending',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: false },
        { id: 'v2', title: 'Verify fee payment', completed: false },
        { id: 'v3', title: 'Confirm site ownership', completed: false },
        { id: 'v4', title: 'Review supporting documents', completed: false },
      ],
    },
    consultation: {
      status: 'not-started',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: false },
        { id: 'c2', title: 'Post site notice', completed: false },
        { id: 'c3', title: 'Notify neighbours', completed: false },
        { id: 'c4', title: 'Review consultation responses', completed: false },
        { id: 'c5', title: 'Prepare consultation summary', completed: false },
      ],
    },
    assessment: {
      status: 'not-started',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: false },
        { id: 'a2', title: 'Assess design and appearance', completed: false },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: false },
        { id: 'a4', title: 'Check conservation considerations', completed: false },
        { id: 'a5', title: 'Prepare recommendation report', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Legal check', completed: false },
        { id: 'r3', title: 'Final decision', completed: false },
      ],
    },
  },
  {
    id: '5',
    reference: 'PA-2025-005',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Michael Brown',
    address: '142 High Street, Bristol, BS1 3NP',
    description: 'Single-storey rear extension',
    status: 'in-validation',
    submittedDate: '2025-10-25',
    validFrom: '2025-10-25',
    consultationEnd: '2025-11-15',
    expiryDate: '2025-11-30',
    isPublic: false,
    requestedServices: ['written-advice', 'site-visit'],
    serviceRecords: [
      {
        id: 'sr-5-1',
        service: 'written-advice',
        status: 'included',
        cost: 500,
      },
      {
        id: 'sr-5-2',
        service: 'site-visit',
        status: 'included',
        cost: 200,
      },
    ],
    totalServiceCost: 700,
    constraints: [],
    documents: [],
    validation: {
      status: 'validated',
      validatedDate: '2025-10-25',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2025-10-25' },
        { id: 'v2', title: 'Verify fee payment', completed: true, completedDate: '2025-10-25' },
        { id: 'v3', title: 'Confirm site ownership', completed: true, completedDate: '2025-10-25' },
        { id: 'v4', title: 'Review supporting documents', completed: true, completedDate: '2025-10-25' },
      ],
    },
    consultation: {
      status: 'not-started',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: false },
        { id: 'c2', title: 'Post site notice', completed: false },
        { id: 'c3', title: 'Notify neighbours', completed: false },
        { id: 'c4', title: 'Review consultation responses', completed: false },
        { id: 'c5', title: 'Prepare consultation summary', completed: false },
      ],
    },
    assessment: {
      status: 'not-started',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: false },
        { id: 'a2', title: 'Assess design and appearance', completed: false },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: false },
        { id: 'a4', title: 'Check conservation considerations', completed: false },
        { id: 'a5', title: 'Prepare recommendation report', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Legal check', completed: false },
        { id: 'r3', title: 'Final decision', completed: false },
      ],
    },
  },
  {
    id: '6',
    reference: 'PA-2025-006',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Emma Wilson',
    address: '78 Church Lane, Cambridge, CB1 2DX',
    description: 'Change of use from office to residential',
    status: 'closed',
    outcome: 'unlikely-supported',
    outcomeDate: '2025-02-10',
    submittedDate: '2024-11-15',
    validFrom: '2024-11-15',
    consultationEnd: '2024-12-06',
    expiryDate: '2024-12-15',
    isPublic: true,
    assignedTo: 'Federico Carbo',
    assignedOfficer: {
      id: 'officer-fc',
      name: 'Federico Carbo',
    },
    requestedServices: ['written-advice', 'meeting'],
    serviceRecords: [
      {
        id: 'sr-6-1',
        service: 'written-advice',
        status: 'included',
        cost: 500,
      },
      {
        id: 'sr-6-2',
        service: 'meeting',
        status: 'included',
        cost: 300,
      },
    ],
    totalServiceCost: 800,
    constraints: [],
    documents: [],
    validation: {
      status: 'validated',
      validatedDate: '2024-11-15',
      tasks: [
        { id: 'v1', title: 'Check application completeness', completed: true, completedDate: '2024-11-15' },
        { id: 'v2', title: 'Verify fee payment', completed: true, completedDate: '2024-11-15' },
        { id: 'v3', title: 'Confirm site ownership', completed: true, completedDate: '2024-11-15' },
        { id: 'v4', title: 'Review supporting documents', completed: true, completedDate: '2024-11-15' },
      ],
    },
    consultation: {
      status: 'completed',
      startDate: '2024-11-15',
      endDate: '2024-12-06',
      tasks: [
        { id: 'c1', title: 'Notify statutory consultees', completed: true, completedDate: '2024-11-15' },
        { id: 'c2', title: 'Post site notice', completed: true, completedDate: '2024-11-16' },
        { id: 'c3', title: 'Notify neighbours', completed: true, completedDate: '2024-11-16' },
        { id: 'c4', title: 'Review consultation responses', completed: true, completedDate: '2024-12-05' },
        { id: 'c5', title: 'Prepare consultation summary', completed: true, completedDate: '2024-12-06' },
      ],
    },
    assessment: {
      status: 'completed',
      startDate: '2024-11-20',
      completedDate: '2024-12-10',
      tasks: [
        { id: 'a1', title: 'Review against planning policy', completed: true, completedDate: '2024-11-20' },
        { id: 'a2', title: 'Assess design and appearance', completed: true, completedDate: '2024-11-25' },
        { id: 'a3', title: 'Evaluate neighbour impact', completed: true, completedDate: '2024-11-30' },
        { id: 'a4', title: 'Check conservation considerations', completed: true, completedDate: '2024-12-05' },
        { id: 'a5', title: 'Prepare recommendation report', completed: true, completedDate: '2024-12-10' },
      ],
    },
    review: {
      status: 'completed',
      startDate: '2024-12-11',
      completedDate: '2024-12-15',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: true, completedDate: '2024-12-11' },
        { id: 'r2', title: 'Legal check', completed: true, completedDate: '2024-12-13' },
        { id: 'r3', title: 'Final decision', completed: true, completedDate: '2024-12-15' },
      ],
    },
  },
  {
    id: '7',
    reference: 'PA-2025-007',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Peter Thompson',
    address: '92 Victoria Road, Oxford, OX1 4RE',
    description: 'Two-storey side extension with new driveway',
    status: 'in-review',
    submittedDate: '2025-09-20',
    validFrom: '2025-09-20',
    consultationEnd: '2025-10-11',
    expiryDate: '2025-11-01',
    isPublic: false,
    assignedTo: 'Federico Carbo',
    assignedOfficer: {
      id: 'officer-fc',
      name: 'Federico Carbo',
    },
    requestedServices: ['written-advice'],
    validation: {
      status: 'validated',
      validatedDate: '2025-09-22',
      tasks: [
        { id: 'v1', title: 'Check application form', completed: true, completedDate: '2025-09-21' },
        { id: 'v2', title: 'Validate documents', completed: true, completedDate: '2025-09-22' },
      ],
    },
    consultation: {
      status: 'completed',
      startDate: '2025-09-23',
      endDate: '2025-10-11',
      tasks: [
        { id: 'c1', title: 'Notify neighbours', completed: true, completedDate: '2025-09-23' },
        { id: 'c2', title: 'Consult statutory bodies', completed: true, completedDate: '2025-09-25' },
      ],
    },
    assessment: {
      status: 'completed',
      startDate: '2025-10-12',
      completedDate: '2025-10-18',
      tasks: [
        { id: 'a1', title: 'Site visit', completed: true, completedDate: '2025-10-13' },
        { id: 'a2', title: 'Policy assessment', completed: true, completedDate: '2025-10-16' },
        { id: 'a3', title: 'Write recommendation', completed: true, completedDate: '2025-10-18' },
      ],
    },
    review: {
      status: 'in-progress',
      startDate: '2025-10-19',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Final approval', completed: false },
      ],
    },
  },
  {
    id: '8',
    reference: 'PA-2025-008',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'Liverpool Developers Ltd',
    address: '15 Elm Avenue, Liverpool, L3 5TY',
    description: 'Demolition of existing garage and construction of new two-storey dwelling',
    status: 'withdrawn',
    submittedDate: '2025-09-10',
    validFrom: '2025-09-10',
    consultationEnd: '2025-10-01',
    expiryDate: '2025-10-15',
    isPublic: true,
    validation: {
      status: 'pending',
      tasks: [
        { id: 'v1', title: 'Check application form', completed: false },
        { id: 'v2', title: 'Validate documents', completed: false },
      ],
    },
    consultation: {
      status: 'not-started',
      tasks: [
        { id: 'c1', title: 'Notify neighbours', completed: false },
        { id: 'c2', title: 'Consult statutory bodies', completed: false },
      ],
    },
    assessment: {
      status: 'not-started',
      tasks: [
        { id: 'a1', title: 'Site visit', completed: false },
        { id: 'a2', title: 'Policy assessment', completed: false },
        { id: 'a3', title: 'Write recommendation', completed: false },
      ],
    },
    review: {
      status: 'not-started',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: false },
        { id: 'r2', title: 'Final approval', completed: false },
      ],
    },
  },
  {
    id: '9',
    reference: 'PA-2025-009',
    type: 'pre-application',
    applicationType: 'Pre-application Advice',
    applicantName: 'James Martinez',
    address: '67 Park Avenue, Sheffield, S10 2PL',
    description: 'Installation of solar panels on south-facing roof slope',
    status: 'closed',
    outcome: 'likely-supported-with-changes',
    outcomeDate: '2025-08-22',
    submittedDate: '2025-07-05',
    validFrom: '2025-07-05',
    consultationEnd: '2025-07-26',
    expiryDate: '2025-08-05',
    isPublic: true,
    assignedTo: 'Bob Smith',
    assignedOfficer: {
      id: 'officer-bs',
      name: 'Bob Smith',
    },
    requestedServices: ['written-advice'],
    validation: {
      status: 'validated',
      validatedDate: '2025-07-07',
      tasks: [
        { id: 'v1', title: 'Check application form', completed: true, completedDate: '2025-07-06' },
        { id: 'v2', title: 'Validate documents', completed: true, completedDate: '2025-07-07' },
      ],
    },
    consultation: {
      status: 'completed',
      startDate: '2025-07-08',
      endDate: '2025-07-26',
      tasks: [
        { id: 'c1', title: 'Notify neighbours', completed: true, completedDate: '2025-07-08' },
        { id: 'c2', title: 'Consult statutory bodies', completed: true, completedDate: '2025-07-10' },
      ],
    },
    assessment: {
      status: 'completed',
      startDate: '2025-07-27',
      completedDate: '2025-08-15',
      tasks: [
        { id: 'a1', title: 'Site visit', completed: true, completedDate: '2025-07-29' },
        { id: 'a2', title: 'Policy assessment', completed: true, completedDate: '2025-08-10' },
        { id: 'a3', title: 'Write recommendation', completed: true, completedDate: '2025-08-15' },
      ],
    },
    review: {
      status: 'completed',
      startDate: '2025-08-16',
      completedDate: '2025-08-22',
      tasks: [
        { id: 'r1', title: 'Senior officer review', completed: true, completedDate: '2025-08-20' },
        { id: 'r2', title: 'Final approval', completed: true, completedDate: '2025-08-22' },
      ],
    },
  },
];

// Helper function to get application by ID
export function getApplicationById(id: string): PlanningApplication | undefined {
  return mockApplications.find(app => app.id === id);
}
